begin;

create table if not exists public.goleadores_oficiales (
  id bigint generated by default as identity primary key,
  torneo_id bigint not null references public.torneos(id),
  posicion integer not null check (posicion > 0),
  equipo_id bigint null references public.clubes(id),
  equipo_nombre text not null check (btrim(equipo_nombre) <> ''),
  jugador_nombre text not null check (btrim(jugador_nombre) <> ''),
  goles integer not null check (goles >= 0),
  fuente text not null check (btrim(fuente) <> ''),
  fecha_fuente date null,
  observaciones text null,
  creado_en timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where
      conname = 'goleadores_oficiales_torneo_posicion_key'
      and conrelid = 'public.goleadores_oficiales'::regclass
  ) then
    alter table public.goleadores_oficiales
      add constraint goleadores_oficiales_torneo_posicion_key
      unique (torneo_id, posicion);
  end if;
end;
$$;

create index if not exists goleadores_oficiales_torneo_goles_idx
  on public.goleadores_oficiales (torneo_id, goles desc, posicion asc);

alter table public.goleadores_oficiales enable row level security;

drop policy if exists goleadores_oficiales_lectura_publica
  on public.goleadores_oficiales;

create policy goleadores_oficiales_lectura_publica
on public.goleadores_oficiales
for select
to anon, authenticated
using (true);

revoke all on table public.goleadores_oficiales
  from public, anon, authenticated;

grant select on table public.goleadores_oficiales
  to anon, authenticated;

grant select, insert, update, delete on table public.goleadores_oficiales
  to service_role;

do $$
declare
  v_sequence text;
begin
  select pg_get_serial_sequence(
    'public.goleadores_oficiales',
    'id'
  )
  into v_sequence;

  if v_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to service_role',
      v_sequence
    );
  end if;
end;
$$;

drop table if exists pg_temp.tmp_goleadores_apertura_2026;

create temporary table tmp_goleadores_apertura_2026 (
  torneo_id bigint not null,
  posicion integer not null,
  equipo_id bigint null,
  equipo_nombre text not null,
  jugador_nombre text not null,
  goles integer not null,
  fuente text not null,
  fecha_fuente date null,
  observaciones text null
) on commit drop;

insert into tmp_goleadores_apertura_2026 (
  torneo_id,
  posicion,
  equipo_id,
  equipo_nombre,
  jugador_nombre,
  goles,
  fuente,
  fecha_fuente,
  observaciones
)
values
  (
    1,
    1,
    47,
    'SPORT C. CAÑADENSE',
    'TOMBOLINI CARLOS DAMIAN',
    13,
    'Tres Palos - selección verificada Apertura 2026',
    null,
    'Goleador destacado conservado por validación manual. No representa tabla completa.'
  ),
  (
    1,
    2,
    47,
    'SPORT C. CAÑADENSE',
    'CARRIZO LAUREANO JOAQUIN',
    9,
    'Tres Palos - selección verificada Apertura 2026',
    null,
    'Goleador destacado conservado por validación manual. No representa tabla completa.'
  ),
  (
    1,
    3,
    43,
    'SPORTIVO A. CLUB',
    'MARTINEZ BRIAN ALEJANDRO',
    9,
    'Tres Palos - selección verificada Apertura 2026',
    null,
    'Goleador destacado conservado por validación manual. No representa tabla completa.'
  ),
  (
    1,
    4,
    46,
    'AD. EVERTON/OLIMPIA',
    'BORINI JULIO CESAR',
    7,
    'Tres Palos - selección verificada Apertura 2026',
    null,
    'Goleador destacado conservado por validación manual. No representa tabla completa.'
  );

delete from public.goleadores_oficiales
where torneo_id = 1;

insert into public.goleadores_oficiales (
  torneo_id,
  posicion,
  equipo_id,
  equipo_nombre,
  jugador_nombre,
  goles,
  fuente,
  fecha_fuente,
  observaciones
)
select
  torneo_id,
  posicion,
  equipo_id,
  equipo_nombre,
  jugador_nombre,
  goles,
  fuente,
  fecha_fuente,
  observaciones
from tmp_goleadores_apertura_2026
on conflict (torneo_id, posicion) do update
set
  equipo_id = excluded.equipo_id,
  equipo_nombre = excluded.equipo_nombre,
  jugador_nombre = excluded.jugador_nombre,
  goles = excluded.goles,
  fuente = excluded.fuente,
  fecha_fuente = excluded.fecha_fuente,
  observaciones = excluded.observaciones;

drop table if exists pg_temp.tmp_goleadores_apertura_2026;

comment on table public.goleadores_oficiales is
  'Snapshot manual de goleadores destacados por torneo. No reemplaza eventos_partido ni futuras vistas calculadas.';

comment on column public.goleadores_oficiales.equipo_nombre is
  'Nombre del equipo tal como figura en la fuente oficial visible.';

comment on column public.goleadores_oficiales.jugador_nombre is
  'Nombre del jugador tal como figura en la fuente oficial visible.';

commit;
