begin;

create table if not exists public.goleadores_oficiales (
  id bigint generated by default as identity primary key,
  torneo_id bigint not null references public.torneos(id),
  posicion integer not null check (posicion > 0),
  equipo_id bigint null references public.clubes(id),
  equipo_nombre text not null check (btrim(equipo_nombre) <> ''),
  jugador_nombre text not null check (btrim(jugador_nombre) <> ''),
  goles integer not null check (goles >= 0),
  fuente text not null check (btrim(fuente) <> ''),
  fecha_fuente date null,
  observaciones text null,
  creado_en timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where
      conname = 'goleadores_oficiales_torneo_posicion_key'
      and conrelid = 'public.goleadores_oficiales'::regclass
  ) then
    alter table public.goleadores_oficiales
      add constraint goleadores_oficiales_torneo_posicion_key
      unique (torneo_id, posicion);
  end if;
end;
$$;

create index if not exists goleadores_oficiales_torneo_goles_idx
  on public.goleadores_oficiales (torneo_id, goles desc, posicion asc);

alter table public.goleadores_oficiales enable row level security;

drop policy if exists goleadores_oficiales_lectura_publica
  on public.goleadores_oficiales;

create policy goleadores_oficiales_lectura_publica
on public.goleadores_oficiales
for select
to anon, authenticated
using (true);

revoke all on table public.goleadores_oficiales
  from public, anon, authenticated;

grant select on table public.goleadores_oficiales
  to anon, authenticated;

grant select, insert, update, delete on table public.goleadores_oficiales
  to service_role;

do $$
declare
  v_sequence text;
begin
  select pg_get_serial_sequence(
    'public.goleadores_oficiales',
    'id'
  )
  into v_sequence;

  if v_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to service_role',
      v_sequence
    );
  end if;
end;
$$;

insert into public.goleadores_oficiales (
  torneo_id,
  posicion,
  equipo_id,
  equipo_nombre,
  jugador_nombre,
  goles,
  fuente,
  fecha_fuente,
  observaciones
)
values
  (
    1,
    1,
    47,
    'SPORT C. CAÑADENSE',
    'TOMBOLINI CARLOS DAMIAN',
    13,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    2,
    47,
    'SPORT C. CAÑADENSE',
    'CARRIZO LAUREANO JOAQUIN',
    9,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    3,
    43,
    'SPORTIVO A. CLUB',
    'MARTINEZ BRIAN ALEJANDRO',
    9,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    4,
    54,
    'DEF. SPORTSMAN',
    'ZABALA MAURICIO',
    9,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    5,
    46,
    'AD.EVERTON/OLIMPIA',
    'BORINI JULIO CESAR',
    7,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    6,
    45,
    'C.A. EL PORVENIR DEL NORTE',
    'BENITEZ CRISTIAN ALFREDO',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    7,
    49,
    'C.A. COSMOPOLITA',
    'CANAL AXEL JOEL',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    8,
    60,
    'C.A. SAN JERONIMO',
    'CANTIANI JUAN BAUTISTA',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    9,
    44,
    'C.A. DEFENSORES',
    'JARA AGUSTIN NAHUEL',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    10,
    58,
    'C.A. AMERICA',
    'JOMINY FRANCO MARCELO',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    11,
    50,
    'C.A. ALMAFUERTE',
    'MOLINA JOAQUIN',
    6,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    12,
    57,
    'C.A. CARCARAÑÁ',
    'BOCCHIETTI MAXIMILIANO CARLOS',
    5,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    13,
    53,
    'C.A. CORREA',
    'CAVALLIN SEBASTIAN',
    5,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    14,
    59,
    'NEWELLS OLD BOYS',
    'MARTINEZ VALENTIN ANGEL',
    5,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    15,
    59,
    'C.A. N.O. BOYS',
    'SANTILLAN ARIEL JULIAN',
    5,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  ),
  (
    1,
    16,
    44,
    'C.A. DEFENSORES',
    'ARBALLO BRUNO EMANUEL',
    4,
    'Liga Cañadense - tabla oficial de goleadores Apertura 2026',
    null,
    'Top visible cargado manualmente desde fuente oficial. Fecha exacta de fuente no informada.'
  )
on conflict (torneo_id, posicion) do update
set
  equipo_id = excluded.equipo_id,
  equipo_nombre = excluded.equipo_nombre,
  jugador_nombre = excluded.jugador_nombre,
  goles = excluded.goles,
  fuente = excluded.fuente,
  fecha_fuente = excluded.fecha_fuente,
  observaciones = excluded.observaciones;

comment on table public.goleadores_oficiales is
  'Snapshot manual de tablas oficiales de goleadores por torneo. No reemplaza eventos_partido ni futuras vistas calculadas.';

comment on column public.goleadores_oficiales.equipo_nombre is
  'Nombre del equipo tal como figura en la fuente oficial visible.';

comment on column public.goleadores_oficiales.jugador_nombre is
  'Nombre del jugador tal como figura en la fuente oficial visible.';

commit;
