create table if not exists public.torneos (
  id bigint generated by default as identity primary key,
  anio smallint not null check (anio between 2000 and 2100),
  tipo text not null check (tipo in ('apertura', 'clausura')),
  nombre text not null,
  activo boolean not null default false,
  fecha_inicio date null,
  fecha_fin date null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (anio, tipo)
);

insert into public.torneos (anio, tipo, nombre, activo)
values
  (2026, 'apertura', 'Apertura 2026', true),
  (2026, 'clausura', 'Clausura 2026', false)
on conflict (anio, tipo) do update
set nombre = excluded.nombre;

create table if not exists public.jugadores (
  id bigint generated by default as identity primary key,
  nombre_completo text not null,
  aliases text[] not null default '{}',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.inscripciones_jugadores (
  id bigint generated by default as identity primary key,
  jugador_id bigint not null references public.jugadores(id),
  club_id bigint not null references public.clubes(id),
  torneo_id bigint not null references public.torneos(id),
  posicion text not null default 'sin_definir' check (
    posicion in (
      'arquero',
      'defensor',
      'mediocampista',
      'delantero',
      'sin_definir'
    )
  ),
  dorsal smallint null check (dorsal between 1 and 99),
  estado text not null default 'por_verificar' check (
    estado in ('confirmado', 'por_verificar', 'inactivo')
  ),
  fecha_desde date null,
  fecha_hasta date null,
  fuente text null,
  observaciones text null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (jugador_id, club_id, torneo_id),
  check (
    fecha_hasta is null
    or fecha_desde is null
    or fecha_hasta >= fecha_desde
  )
);

alter table public.partidos
  add column if not exists torneo_id bigint null;

update public.partidos
set torneo_id = (
  select id
  from public.torneos
  where anio = 2026 and tipo = 'apertura'
  limit 1
)
where torneo_id is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where
      conname = 'partidos_torneo_fk'
      and conrelid = 'public.partidos'::regclass
  ) then
    alter table public.partidos
      add constraint partidos_torneo_fk
      foreign key (torneo_id)
      references public.torneos(id)
      not valid;
  end if;
end;
$$;

alter table public.partidos
  validate constraint partidos_torneo_fk;

create index if not exists partidos_torneo_idx
  on public.partidos (torneo_id);

create index if not exists inscripciones_club_torneo_idx
  on public.inscripciones_jugadores (club_id, torneo_id, estado);

create index if not exists inscripciones_jugador_idx
  on public.inscripciones_jugadores (jugador_id);

create index if not exists jugadores_nombre_idx
  on public.jugadores (nombre_completo);

alter table public.torneos enable row level security;
alter table public.jugadores enable row level security;
alter table public.inscripciones_jugadores enable row level security;

drop policy if exists torneos_lectura_publica on public.torneos;
create policy torneos_lectura_publica
on public.torneos
for select
to anon, authenticated
using (true);

drop policy if exists jugadores_lectura_publica on public.jugadores;
create policy jugadores_lectura_publica
on public.jugadores
for select
to anon, authenticated
using (true);

drop policy if exists inscripciones_lectura_publica
  on public.inscripciones_jugadores;
create policy inscripciones_lectura_publica
on public.inscripciones_jugadores
for select
to anon, authenticated
using (true);

do $$
begin
  if to_regclass('public.eventos_partido') is not null then
    execute
      'alter table public.eventos_partido ' ||
      'add column if not exists inscripcion_jugador_id bigint null';

    if not exists (
      select 1
      from pg_constraint
      where
        conname = 'eventos_partido_inscripcion_fk'
        and conrelid = 'public.eventos_partido'::regclass
    ) then
      alter table public.eventos_partido
        add constraint eventos_partido_inscripcion_fk
        foreign key (inscripcion_jugador_id)
        references public.inscripciones_jugadores(id)
        not valid;
    end if;

    alter table public.eventos_partido
      validate constraint eventos_partido_inscripcion_fk;

    execute
      'create index if not exists eventos_partido_inscripcion_idx ' ||
      'on public.eventos_partido (inscripcion_jugador_id)';
  end if;
end;
$$;

create or replace function public.admin_guardar_inscripcion_jugador(
  p_inscripcion_id bigint default null,
  p_jugador_id bigint default null,
  p_nombre_completo text default null,
  p_aliases text[] default '{}',
  p_club_id bigint default null,
  p_torneo_id bigint default null,
  p_posicion text default 'sin_definir',
  p_dorsal smallint default null,
  p_estado text default 'por_verificar',
  p_fecha_desde date default null,
  p_fecha_hasta date default null,
  p_fuente text default null,
  p_observaciones text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_jugador public.jugadores;
  v_inscripcion public.inscripciones_jugadores;
begin
  if p_club_id is null or p_torneo_id is null then
    raise exception 'Club y torneo son obligatorios.';
  end if;

  if p_nombre_completo is null or btrim(p_nombre_completo) = '' then
    raise exception 'El nombre del jugador es obligatorio.';
  end if;

  if p_posicion not in (
    'arquero',
    'defensor',
    'mediocampista',
    'delantero',
    'sin_definir'
  ) then
    raise exception 'Posicion invalida.';
  end if;

  if p_estado not in ('confirmado', 'por_verificar', 'inactivo') then
    raise exception 'Estado invalido.';
  end if;

  if
    p_estado = 'confirmado'
    and (p_fuente is null or btrim(p_fuente) = '')
  then
    raise exception 'Un jugador confirmado debe tener una fuente.';
  end if;

  if p_dorsal is not null and (p_dorsal < 1 or p_dorsal > 99) then
    raise exception 'Dorsal invalido.';
  end if;

  if
    p_fecha_desde is not null
    and p_fecha_hasta is not null
    and p_fecha_hasta < p_fecha_desde
  then
    raise exception 'La fecha hasta no puede ser anterior a fecha desde.';
  end if;

  if p_inscripcion_id is not null then
    select *
    into v_inscripcion
    from public.inscripciones_jugadores
    where id = p_inscripcion_id
    for update;

    if not found then
      raise exception 'Inscripcion no encontrada.';
    end if;

    p_jugador_id := v_inscripcion.jugador_id;
  end if;

  if p_jugador_id is null then
    insert into public.jugadores (
      nombre_completo,
      aliases
    )
    values (
      btrim(p_nombre_completo),
      coalesce(p_aliases, '{}')
    )
    returning * into v_jugador;
  else
    update public.jugadores
    set
      nombre_completo = btrim(p_nombre_completo),
      aliases = coalesce(p_aliases, '{}'),
      actualizado_en = now()
    where id = p_jugador_id
    returning * into v_jugador;

    if not found then
      raise exception 'Jugador no encontrado.';
    end if;
  end if;

  if p_inscripcion_id is null then
    insert into public.inscripciones_jugadores (
      jugador_id,
      club_id,
      torneo_id,
      posicion,
      dorsal,
      estado,
      fecha_desde,
      fecha_hasta,
      fuente,
      observaciones
    )
    values (
      v_jugador.id,
      p_club_id,
      p_torneo_id,
      p_posicion,
      p_dorsal,
      p_estado,
      p_fecha_desde,
      p_fecha_hasta,
      nullif(btrim(p_fuente), ''),
      nullif(btrim(p_observaciones), '')
    )
    returning * into v_inscripcion;
  else
    update public.inscripciones_jugadores
    set
      club_id = p_club_id,
      torneo_id = p_torneo_id,
      posicion = p_posicion,
      dorsal = p_dorsal,
      estado = p_estado,
      fecha_desde = p_fecha_desde,
      fecha_hasta = p_fecha_hasta,
      fuente = nullif(btrim(p_fuente), ''),
      observaciones = nullif(btrim(p_observaciones), ''),
      actualizado_en = now()
    where id = p_inscripcion_id
    returning * into v_inscripcion;
  end if;

  return jsonb_build_object(
    'jugador', to_jsonb(v_jugador),
    'inscripcion', to_jsonb(v_inscripcion)
  );
end;
$$;

grant select on table public.torneos to anon, authenticated;
grant select on table public.jugadores to anon, authenticated;
grant select on table public.inscripciones_jugadores to anon, authenticated;

grant select, insert, update on table public.torneos to service_role;
grant select, insert, update on table public.jugadores to service_role;
grant select, insert, update on table public.inscripciones_jugadores
  to service_role;

grant usage, select on sequence public.torneos_id_seq to service_role;
grant usage, select on sequence public.jugadores_id_seq to service_role;
grant usage, select on sequence public.inscripciones_jugadores_id_seq
  to service_role;

revoke all on function public.admin_guardar_inscripcion_jugador(
  bigint,
  bigint,
  text,
  text[],
  bigint,
  bigint,
  text,
  smallint,
  text,
  date,
  date,
  text,
  text
) from public, anon, authenticated;

grant execute on function public.admin_guardar_inscripcion_jugador(
  bigint,
  bigint,
  text,
  text[],
  bigint,
  bigint,
  text,
  smallint,
  text,
  date,
  date,
  text,
  text
) to service_role;

comment on table public.jugadores is
  'Identidad permanente de cada jugador, independiente del club.';

comment on table public.inscripciones_jugadores is
  'Participacion de un jugador en un club y torneo determinados.';
