-- Prevalidacion solo lectura - Clausura 2026.
-- Ejecutar en Supabase SQL Editor antes de reintentar la carga.
-- No modifica datos remotos.

do $$
declare
  v_fixture constant jsonb := $fixture_json$
[
  {
    "source_fixture_key": "C2026-F01-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 46,
    "local": "C.A. Cosmopolita",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 54,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 53,
    "local": "Sportivo A. Club",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 61,
    "local": "C.A. Am\u00e9rica",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 56,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 59,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 62,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 45,
    "local": "C.A. Defensores",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 63,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 55,
    "local": "AD Everton/Olimpia",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 47,
    "local": "C.A. Correa",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 49,
    "local": "Def. Sportsman",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 52,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 48,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 59,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 44,
    "local": "C.A. Barraca",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 51,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 60,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 54,
    "local": "Argentino A. Club",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 53,
    "local": "C.A. Cosmopolita",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 43,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 58,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 56,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 61,
    "local": "C.A. N.O. Boys",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 62,
    "local": "C.A. Defensores",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 50,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 63,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 55,
    "local": "C.A. Correa",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 46,
    "local": "Def. Sportsman",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 49,
    "local": "Sportivo A. Club",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 56,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 59,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 48,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 44,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 45,
    "local": "C.A. Barraca",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 51,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 53,
    "local": "AD Everton/Olimpia",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 43,
    "local": "Argentino A. Club",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 47,
    "local": "C.A. Cosmopolita",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 61,
    "local": "C.A. Montes de Oca",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 52,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 58,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 60,
    "local": "C.A. Defensores",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 62,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 50,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 54,
    "local": "C.A. Correa",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 55,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 46,
    "local": "Sportivo A. Club",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 45,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 51,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 63,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 47,
    "local": "AD Everton/Olimpia",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 49,
    "local": "Argentino A. Club",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 43,
    "local": "Def. Sportsman",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 50,
    "local": "C.A. Barraca",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 60,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 44,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 49,
    "local": "AD Everton/Olimpia",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 43,
    "local": "C.A. Correa",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 47,
    "local": "Def. Sportsman",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 58,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 48,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 52,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 60,
    "local": "C.A. Barraca",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 44,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 50,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 46,
    "local": "Argentino A. Club",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 54,
    "local": "C.A. Cosmopolita",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 53,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 61,
    "local": "C.A. Campa\u00f1a",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 58,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 56,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 63,
    "local": "C.A. Defensores",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 62,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 45,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 49,
    "local": "C.A. Correa",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 55,
    "local": "Def. Sportsman",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 47,
    "local": "Sportivo A. Club",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 59,
    "local": "Belgrano A.C.",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 52,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 48,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 60,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 51,
    "local": "C.A. Barraca",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 44,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 54,
    "local": "AD Everton/Olimpia",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 53,
    "local": "Argentino A. Club",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 43,
    "local": "C.A. Cosmopolita",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 52,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 58,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 61,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 50,
    "local": "C.A. Defensores",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 63,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 62,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 46,
    "local": "C.A. Correa",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 49,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 55,
    "local": "Sportivo A. Club",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 48,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 56,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 59,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 51,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 44,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 45,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 43,
    "local": "AD Everton/Olimpia",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 47,
    "local": "Argentino A. Club",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 53,
    "local": "Def. Sportsman",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 62,
    "local": "C.A. Barraca",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 50,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 60,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 55,
    "local": "C.A. Cosmopolita",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 46,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 54,
    "local": "Sportivo A. Club",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 63,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 51,
    "local": "C.A. Defensores",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 45,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  }
]
$fixture_json$::jsonb;
  v_expected_clubs constant jsonb := $clubs_json$
[
  {
    "nombre_fuente": "C.A. COSMOPOLITA",
    "nombre_en_proyecto": "C.A. Cosmopolita",
    "club_id": 49,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "SPORT C. CA\u00d1ADENSE",
    "nombre_en_proyecto": "Sport C. Ca\u00f1adense",
    "club_id": 47,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "SPORTIVO A. CLUB",
    "nombre_en_proyecto": "Sportivo A. Club",
    "club_id": 43,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. CORREA",
    "nombre_en_proyecto": "C.A. Correa",
    "club_id": 53,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "DEF. SPORTSMAN",
    "nombre_en_proyecto": "Def. Sportsman",
    "club_id": 54,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "AD.EVERTON/OLIMPIA",
    "nombre_en_proyecto": "AD Everton/Olimpia",
    "club_id": 46,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "ARGENTINO A. CLUB",
    "nombre_en_proyecto": "Argentino A. Club",
    "club_id": 55,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. MONTES DE OCA",
    "nombre_en_proyecto": "C.A. Montes de Oca",
    "club_id": 48,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. N.O. BOYS",
    "nombre_en_proyecto": "C.A. N.O. Boys",
    "club_id": 59,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. CAMPA\u00d1A",
    "nombre_en_proyecto": "C.A. Campa\u00f1a",
    "club_id": 52,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. UNION C.S.D.",
    "nombre_en_proyecto": "C.A. Uni\u00f3n C.S.D.",
    "club_id": 56,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. AMERICA",
    "nombre_en_proyecto": "C.A. Am\u00e9rica",
    "club_id": 58,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "BELGRANO A.C.",
    "nombre_en_proyecto": "Belgrano A.C.",
    "club_id": 61,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. DEFENSORES",
    "nombre_en_proyecto": "C.A. Defensores",
    "club_id": 44,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. SAN JERONIMO",
    "nombre_en_proyecto": "C.A. San Jer\u00f3nimo",
    "club_id": 60,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. ALMAFUERTE",
    "nombre_en_proyecto": "C.A. Almafuerte",
    "club_id": 50,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. UNION TORTUGAS",
    "nombre_en_proyecto": "C.A. Uni\u00f3n Tortugas",
    "club_id": 62,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. BARRACA",
    "nombre_en_proyecto": "C.A. Barraca",
    "club_id": 63,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. EL PORVENIR DEL NORTE",
    "nombre_en_proyecto": "C.A. El Porvenir del Norte",
    "club_id": 45,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A.WILLIAMS KEMMIS",
    "nombre_en_proyecto": "C.A. Williams Kemmis",
    "club_id": 51,
    "zona_clausura": 3,
    "estado": "confirmado"
  }
]
$clubs_json$::jsonb;
  v_bad integer := 0;
  v_type_errors text := null;
begin
  if not exists (
    select 1
    from public.torneos
    where id = 2
      and anio = 2026
      and tipo = 'clausura'
      and nombre = 'Clausura 2026'
      and activo is false
  ) then
    raise exception 'Prevalidacion: torneo_id=2 no corresponde a Clausura 2026 inactivo.';
  end if;

  if not exists (
    select 1
    from public.torneos
    where id = 1
      and anio = 2026
      and tipo = 'apertura'
      and nombre = 'Apertura 2026'
      and activo is true
  ) then
    raise exception 'Prevalidacion: Apertura 2026 id 1 no es el torneo activo.';
  end if;

  select count(*)
  into v_bad
  from public.partidos
  where torneo_id = 2;

  if v_bad <> 0 then
    raise exception 'Prevalidacion: Clausura ya tiene % partido(s).', v_bad;
  end if;

  select count(*)
  into v_bad
  from public.partidos
  where torneo_id = 1;

  if v_bad <> 140 then
    raise exception 'Prevalidacion: Apertura debe tener 140 partidos y tiene %.', v_bad;
  end if;

  select count(*)
  into v_bad
  from public.partidos
  where torneo_id = 1
    and tipo = 'regular'
    and (
      source_local is not null
      or source_visitante is not null
    );

  if v_bad <> 0 then
    raise exception 'Prevalidacion: la fase regular del Apertura usa source_local/source_visitante.';
  end if;

  select count(*)
  into v_bad
  from jsonb_to_recordset(v_expected_clubs) as expected(
    nombre_fuente text,
    nombre_en_proyecto text,
    club_id bigint,
    zona_clausura integer,
    estado text
  )
  left join public.clubes club
    on club.id = expected.club_id
  where club.id is null
    or club.nombre_oficial is distinct from expected.nombre_en_proyecto
    or club.activo is false
    or expected.estado is distinct from 'confirmado';

  if v_bad <> 0 then
    raise exception 'Prevalidacion: hay % club(es) esperados sin mapeo remoto confirmado.', v_bad;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  )
  select count(*)
  into v_bad
  from fixture;

  if v_bad <> 114 then
    raise exception 'Prevalidacion: el fixture debe tener 114 registros y tiene %.', v_bad;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  )
  select count(*)
  into v_bad
  from fixture
  where torneo_id <> 2
    or tipo <> 'regular'
    or fecha is null
    or zona not in ('1', '2', '3')
    or local_id is null
    or visitante_id is null
    or local_id = visitante_id
    or local is null
    or visitante is null
    or fecha_partido is not null
    or dia is not null
    or hora is not null
    or estadio is not null
    or arbitro is not null
    or estado <> 'programado'
    or goles_local is not null
    or goles_visitante is not null
    or penales_local is not null
    or penales_visitante is not null
    or fase is not null
    or numero_playoff is not null
    or source_local is not null
    or source_visitante is not null
    or local_id = 57
    or visitante_id = 57;

  if v_bad <> 0 then
    raise exception 'Prevalidacion: hay % registro(s) del fixture con campos invalidos.', v_bad;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  )
  select count(*)
  into v_bad
  from (
    select torneo_id, tipo, fecha, zona, local_id, visitante_id
    from fixture
    group by torneo_id, tipo, fecha, zona, local_id, visitante_id
    having count(*) > 1
  ) duplicated_fixture;

  if v_bad <> 0 then
    raise exception 'Prevalidacion: el fixture contiene % clave(s) logicas duplicadas.', v_bad;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  )
  select string_agg(
    campo || ': partidos=' || tipo_partidos || ', fixture=' || tipo_fixture,
    '; '
    order by campo
  )
  into v_type_errors
  from (
    select
      'fecha' as campo,
      pg_typeof(partido.fecha)::text as tipo_partidos,
      pg_typeof(fixture.fecha)::text as tipo_fixture
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
    union all
    select 'local_id', pg_typeof(partido.local_id)::text, pg_typeof(fixture.local_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
    union all
    select 'tipo', pg_typeof(partido.tipo)::text, pg_typeof(fixture.tipo)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
    union all
    select 'torneo_id', pg_typeof(partido.torneo_id)::text, pg_typeof(fixture.torneo_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
    union all
    select 'visitante_id', pg_typeof(partido.visitante_id)::text, pg_typeof(fixture.visitante_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
    union all
    select 'zona', pg_typeof(partido.zona)::text, pg_typeof(fixture.zona)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido
    cross join (select * from fixture limit 1) fixture
  ) type_check
  where tipo_partidos is distinct from tipo_fixture;

  if v_type_errors is not null then
    raise exception 'Prevalidacion: tipos incompatibles: %.', v_type_errors;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  )
  select count(*)
  into v_bad
  from fixture
  where exists (
    select 1
    from public.partidos partido
    where partido.torneo_id = fixture.torneo_id
      and partido.tipo = fixture.tipo
      and partido.fecha = fixture.fecha
      and partido.zona = fixture.zona
      and partido.local_id = fixture.local_id
      and partido.visitante_id = fixture.visitante_id
  );

  if v_bad <> 0 then
    raise exception 'Prevalidacion: hay % partido(s) del Clausura ya existentes.', v_bad;
  end if;

  with fixture as (
    select *
    from jsonb_to_recordset(v_fixture) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id bigint,
    visitante_id bigint,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
  ),
  sample as (
    select *
    from public.partidos
    where torneo_id = 1
    limit 1
  )
  select count(*)
  into v_bad
  from sample partido
  cross join (select * from fixture limit 1) fixture
  where partido.torneo_id = fixture.torneo_id
    and partido.tipo = fixture.tipo
    and partido.fecha = fixture.fecha
    and partido.zona = fixture.zona
    and partido.local_id = fixture.local_id
    and partido.visitante_id = fixture.visitante_id
    and partido.local is not distinct from fixture.local
    and partido.visitante is not distinct from fixture.visitante
    and partido.estado is not distinct from fixture.estado
    and partido.goles_local is not distinct from fixture.goles_local
    and partido.goles_visitante is not distinct from fixture.goles_visitante
    and partido.penales_local is not distinct from fixture.penales_local
    and partido.penales_visitante is not distinct from fixture.penales_visitante
    and partido.fase is not distinct from fixture.fase
    and partido.numero_playoff is not distinct from fixture.numero_playoff
    and partido.fecha_partido is not distinct from fixture.fecha_partido
    and partido.dia is not distinct from fixture.dia
    and partido.hora is not distinct from fixture.hora
    and partido.estadio is not distinct from fixture.estadio
    and partido.arbitro is not distinct from fixture.arbitro
    and partido.source_local is not distinct from fixture.source_local
    and partido.source_visitante is not distinct from fixture.source_visitante;

  raise notice 'Prevalidacion Clausura 2026 aprobada: fixture 114, Clausura 0, Apertura 140, tipos compatibles.';
end;
$$;
