-- Prevalidacion solo lectura - Clausura 2026.
-- Ejecutar en Supabase SQL Editor antes de reintentar la carga.
-- Devuelve una fila; no modifica datos remotos.

with fixture_json as (
  select $fixture_json$
[
  {
    "source_fixture_key": "C2026-F01-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 46,
    "local": "C.A. Cosmopolita",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 54,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 53,
    "local": "Sportivo A. Club",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 61,
    "local": "C.A. Am\u00e9rica",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 56,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 59,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 62,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 45,
    "local": "C.A. Defensores",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F01-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 1,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 63,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 55,
    "local": "AD Everton/Olimpia",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 47,
    "local": "C.A. Correa",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 49,
    "local": "Def. Sportsman",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 52,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 48,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 59,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 44,
    "local": "C.A. Barraca",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 51,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F02-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 2,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 60,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 54,
    "local": "Argentino A. Club",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 53,
    "local": "C.A. Cosmopolita",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 43,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 58,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 56,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 61,
    "local": "C.A. N.O. Boys",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 62,
    "local": "C.A. Defensores",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 50,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F03-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 3,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 63,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 55,
    "local": "C.A. Correa",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 46,
    "local": "Def. Sportsman",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 49,
    "local": "Sportivo A. Club",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 56,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 59,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 48,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 44,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 45,
    "local": "C.A. Barraca",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F04-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 4,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 51,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 53,
    "local": "AD Everton/Olimpia",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 43,
    "local": "Argentino A. Club",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 47,
    "local": "C.A. Cosmopolita",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 61,
    "local": "C.A. Montes de Oca",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 52,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 58,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 60,
    "local": "C.A. Defensores",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 62,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F05-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 5,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 50,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 54,
    "local": "C.A. Correa",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 55,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 46,
    "local": "Sportivo A. Club",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 45,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 51,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F06-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 6,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 63,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 47,
    "local": "AD Everton/Olimpia",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 49,
    "local": "Argentino A. Club",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 43,
    "local": "Def. Sportsman",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 50,
    "local": "C.A. Barraca",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 60,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F07-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 7,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 44,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 49,
    "local": "AD Everton/Olimpia",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 43,
    "local": "C.A. Correa",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 47,
    "local": "Def. Sportsman",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 58,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 48,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 52,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 60,
    "local": "C.A. Barraca",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 44,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F08-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 8,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 50,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 46,
    "local": "Argentino A. Club",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 54,
    "local": "C.A. Cosmopolita",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 53,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 61,
    "local": "C.A. Campa\u00f1a",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 58,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 56,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 63,
    "local": "C.A. Defensores",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 62,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F09-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 9,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 45,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 49,
    "local": "C.A. Correa",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 55,
    "local": "Def. Sportsman",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 47,
    "local": "Sportivo A. Club",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 59,
    "local": "Belgrano A.C.",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 52,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 48,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 60,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 51,
    "local": "C.A. Barraca",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F10-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 10,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 44,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 54,
    "local": "AD Everton/Olimpia",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 53,
    "local": "Argentino A. Club",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 43,
    "local": "C.A. Cosmopolita",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 48,
    "visitante_id": 52,
    "local": "C.A. Montes de Oca",
    "visitante": "C.A. Campa\u00f1a",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 59,
    "visitante_id": 58,
    "local": "C.A. N.O. Boys",
    "visitante": "C.A. Am\u00e9rica",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 2,
    "local_id": 56,
    "visitante_id": 61,
    "local": "C.A. Uni\u00f3n C.S.D.",
    "visitante": "Belgrano A.C.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 50,
    "local": "C.A. Defensores",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 63,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F11-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 11,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 62,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 53,
    "visitante_id": 46,
    "local": "C.A. Correa",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 49,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "C.A. Cosmopolita",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 55,
    "local": "Sportivo A. Club",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 61,
    "visitante_id": 48,
    "local": "Belgrano A.C.",
    "visitante": "C.A. Montes de Oca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 58,
    "visitante_id": 56,
    "local": "C.A. Am\u00e9rica",
    "visitante": "C.A. Uni\u00f3n C.S.D.",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z2-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 2,
    "local_id": 52,
    "visitante_id": 59,
    "local": "C.A. Campa\u00f1a",
    "visitante": "C.A. N.O. Boys",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 51,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 44,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. Defensores",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F12-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 12,
    "zona": 3,
    "local_id": 62,
    "visitante_id": 45,
    "local": "C.A. Uni\u00f3n Tortugas",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 46,
    "visitante_id": 43,
    "local": "AD Everton/Olimpia",
    "visitante": "Sportivo A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 55,
    "visitante_id": 47,
    "local": "Argentino A. Club",
    "visitante": "Sport C. Ca\u00f1adense",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 1,
    "local_id": 54,
    "visitante_id": 53,
    "local": "Def. Sportsman",
    "visitante": "C.A. Correa",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 63,
    "visitante_id": 62,
    "local": "C.A. Barraca",
    "visitante": "C.A. Uni\u00f3n Tortugas",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 45,
    "visitante_id": 50,
    "local": "C.A. El Porvenir del Norte",
    "visitante": "C.A. Almafuerte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F13-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 13,
    "zona": 3,
    "local_id": 51,
    "visitante_id": 60,
    "local": "C.A. Williams Kemmis",
    "visitante": "C.A. San Jer\u00f3nimo",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 49,
    "visitante_id": 55,
    "local": "C.A. Cosmopolita",
    "visitante": "Argentino A. Club",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 47,
    "visitante_id": 46,
    "local": "Sport C. Ca\u00f1adense",
    "visitante": "AD Everton/Olimpia",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z1-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 1,
    "local_id": 43,
    "visitante_id": 54,
    "local": "Sportivo A. Club",
    "visitante": "Def. Sportsman",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-01",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 50,
    "visitante_id": 63,
    "local": "C.A. Almafuerte",
    "visitante": "C.A. Barraca",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-02",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 44,
    "visitante_id": 51,
    "local": "C.A. Defensores",
    "visitante": "C.A. Williams Kemmis",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  },
  {
    "source_fixture_key": "C2026-F14-Z3-03",
    "torneo_id": 2,
    "tipo": "regular",
    "fecha": 14,
    "zona": 3,
    "local_id": 60,
    "visitante_id": 45,
    "local": "C.A. San Jer\u00f3nimo",
    "visitante": "C.A. El Porvenir del Norte",
    "fecha_partido": null,
    "dia": null,
    "hora": null,
    "estadio": null,
    "arbitro": null,
    "estado": "programado",
    "goles_local": null,
    "goles_visitante": null,
    "penales_local": null,
    "penales_visitante": null,
    "fase": null,
    "numero_playoff": null,
    "source_local": null,
    "source_visitante": null
  }
]
$fixture_json$::jsonb as data
),
expected_clubs_json as (
  select $clubs_json$
[
  {
    "nombre_fuente": "C.A. COSMOPOLITA",
    "nombre_en_proyecto": "C.A. Cosmopolita",
    "club_id": 49,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "SPORT C. CA\u00d1ADENSE",
    "nombre_en_proyecto": "Sport C. Ca\u00f1adense",
    "club_id": 47,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "SPORTIVO A. CLUB",
    "nombre_en_proyecto": "Sportivo A. Club",
    "club_id": 43,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. CORREA",
    "nombre_en_proyecto": "C.A. Correa",
    "club_id": 53,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "DEF. SPORTSMAN",
    "nombre_en_proyecto": "Def. Sportsman",
    "club_id": 54,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "AD.EVERTON/OLIMPIA",
    "nombre_en_proyecto": "AD Everton/Olimpia",
    "club_id": 46,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "ARGENTINO A. CLUB",
    "nombre_en_proyecto": "Argentino A. Club",
    "club_id": 55,
    "zona_clausura": 1,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. MONTES DE OCA",
    "nombre_en_proyecto": "C.A. Montes de Oca",
    "club_id": 48,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. N.O. BOYS",
    "nombre_en_proyecto": "C.A. N.O. Boys",
    "club_id": 59,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. CAMPA\u00d1A",
    "nombre_en_proyecto": "C.A. Campa\u00f1a",
    "club_id": 52,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. UNION C.S.D.",
    "nombre_en_proyecto": "C.A. Uni\u00f3n C.S.D.",
    "club_id": 56,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. AMERICA",
    "nombre_en_proyecto": "C.A. Am\u00e9rica",
    "club_id": 58,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "BELGRANO A.C.",
    "nombre_en_proyecto": "Belgrano A.C.",
    "club_id": 61,
    "zona_clausura": 2,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. DEFENSORES",
    "nombre_en_proyecto": "C.A. Defensores",
    "club_id": 44,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. SAN JERONIMO",
    "nombre_en_proyecto": "C.A. San Jer\u00f3nimo",
    "club_id": 60,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. ALMAFUERTE",
    "nombre_en_proyecto": "C.A. Almafuerte",
    "club_id": 50,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. UNION TORTUGAS",
    "nombre_en_proyecto": "C.A. Uni\u00f3n Tortugas",
    "club_id": 62,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. BARRACA",
    "nombre_en_proyecto": "C.A. Barraca",
    "club_id": 63,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A. EL PORVENIR DEL NORTE",
    "nombre_en_proyecto": "C.A. El Porvenir del Norte",
    "club_id": 45,
    "zona_clausura": 3,
    "estado": "confirmado"
  },
  {
    "nombre_fuente": "C.A.WILLIAMS KEMMIS",
    "nombre_en_proyecto": "C.A. Williams Kemmis",
    "club_id": 51,
    "zona_clausura": 3,
    "estado": "confirmado"
  }
]
$clubs_json$::jsonb as data
),
fixture as (
  select item.*
  from fixture_json
  cross join lateral jsonb_to_recordset(fixture_json.data) as item(
    source_fixture_key text,
    torneo_id bigint,
    tipo text,
    fecha integer,
    zona text,
    local_id integer,
    visitante_id integer,
    local text,
    visitante text,
    fecha_partido date,
    dia text,
    hora text,
    estadio text,
    arbitro text,
    estado text,
    goles_local integer,
    goles_visitante integer,
    penales_local integer,
    penales_visitante integer,
    fase text,
    numero_playoff integer,
    source_local text,
    source_visitante text
  )
),
expected_clubs as (
  select expected.*
  from expected_clubs_json
  cross join lateral jsonb_to_recordset(expected_clubs_json.data) as expected(
    nombre_fuente text,
    nombre_en_proyecto text,
    club_id bigint,
    zona_clausura integer,
    estado text
  )
),
apertura as (
  select count(*) as total
  from public.partidos
  where torneo_id = 1
),
clausura as (
  select count(*) as total
  from public.partidos
  where torneo_id = 2
),
fixture_total as (
  select count(*) as total
  from fixture
),
fixture_invalidos as (
  select count(*) as total
  from fixture
  where torneo_id <> 2
    or tipo <> 'regular'
    or fecha is null
    or zona not in ('1', '2', '3')
    or local_id is null
    or visitante_id is null
    or local_id = visitante_id
    or local is null
    or visitante is null
    or fecha_partido is not null
    or dia is not null
    or hora is not null
    or estadio is not null
    or arbitro is not null
    or estado <> 'programado'
    or goles_local is not null
    or goles_visitante is not null
    or penales_local is not null
    or penales_visitante is not null
    or fase is not null
    or numero_playoff is not null
    or source_local is not null
    or source_visitante is not null
    or local_id = 57
    or visitante_id = 57
),
fixture_duplicados as (
  select count(*) as total
  from (
    select torneo_id, tipo, fecha, zona, local_id, visitante_id
    from fixture
    group by torneo_id, tipo, fecha, zona, local_id, visitante_id
    having count(*) > 1
  ) duplicados
),
clubes_invalidos as (
  select count(*) as total
  from expected_clubs expected
  left join public.clubes club
    on club.id = expected.club_id
  where club.id is null
    or club.nombre_oficial is distinct from expected.nombre_en_proyecto
    or club.activo is false
    or expected.estado is distinct from 'confirmado'
),
existing_matches as (
  select
    fixture.*,
    partido.id as partido_id,
    partido.fecha_partido as p_fecha_partido,
    partido.dia as p_dia,
    partido.hora as p_hora,
    partido.estadio as p_estadio,
    partido.arbitro as p_arbitro,
    partido.estado as p_estado,
    partido.goles_local as p_goles_local,
    partido.goles_visitante as p_goles_visitante,
    partido.penales_local as p_penales_local,
    partido.penales_visitante as p_penales_visitante,
    partido.fase as p_fase,
    partido.numero_playoff as p_numero_playoff,
    partido.local as p_local,
    partido.visitante as p_visitante,
    partido.source_local as p_source_local,
    partido.source_visitante as p_source_visitante
  from fixture
  join public.partidos partido
    on partido.torneo_id = fixture.torneo_id
    and partido.tipo = fixture.tipo
    and partido.fecha = fixture.fecha
    and partido.zona = fixture.zona
    and partido.local_id = fixture.local_id
    and partido.visitante_id = fixture.visitante_id
),
conflictos as (
  select count(*) as total
  from existing_matches
  where not (
    p_local is not distinct from local
      and p_visitante is not distinct from visitante
      and p_fecha_partido is not distinct from fecha_partido
      and p_dia is not distinct from dia
      and p_hora is not distinct from hora
      and p_estadio is not distinct from estadio
      and p_arbitro is not distinct from arbitro
      and p_estado is not distinct from estado
      and p_goles_local is not distinct from goles_local
      and p_goles_visitante is not distinct from goles_visitante
      and p_penales_local is not distinct from penales_local
      and p_penales_visitante is not distinct from penales_visitante
      and p_fase is not distinct from fase
      and p_numero_playoff is not distinct from numero_playoff
      and p_source_local is not distinct from source_local
      and p_source_visitante is not distinct from source_visitante
  )
),
type_checks as (
  select
    campo,
    tipo_partidos,
    tipo_fixture,
    tipo_partidos = tipo_fixture as ok
  from (
    select 'arbitro' as campo, pg_typeof(partido.arbitro)::text as tipo_partidos, pg_typeof(fixture.arbitro)::text as tipo_fixture
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'dia', pg_typeof(partido.dia)::text, pg_typeof(fixture.dia)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'estado', pg_typeof(partido.estado)::text, pg_typeof(fixture.estado)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'estadio', pg_typeof(partido.estadio)::text, pg_typeof(fixture.estadio)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'fase', pg_typeof(partido.fase)::text, pg_typeof(fixture.fase)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'fecha', pg_typeof(partido.fecha)::text, pg_typeof(fixture.fecha)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'fecha_partido', pg_typeof(partido.fecha_partido)::text, pg_typeof(fixture.fecha_partido)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'goles_local', pg_typeof(partido.goles_local)::text, pg_typeof(fixture.goles_local)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'goles_visitante', pg_typeof(partido.goles_visitante)::text, pg_typeof(fixture.goles_visitante)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'hora', pg_typeof(partido.hora)::text, pg_typeof(fixture.hora)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'local', pg_typeof(partido.local)::text, pg_typeof(fixture.local)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'local_id', pg_typeof(partido.local_id)::text, pg_typeof(fixture.local_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'numero_playoff', pg_typeof(partido.numero_playoff)::text, pg_typeof(fixture.numero_playoff)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'penales_local', pg_typeof(partido.penales_local)::text, pg_typeof(fixture.penales_local)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'penales_visitante', pg_typeof(partido.penales_visitante)::text, pg_typeof(fixture.penales_visitante)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'source_local', pg_typeof(partido.source_local)::text, pg_typeof(fixture.source_local)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'source_visitante', pg_typeof(partido.source_visitante)::text, pg_typeof(fixture.source_visitante)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'tipo', pg_typeof(partido.tipo)::text, pg_typeof(fixture.tipo)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'torneo_id', pg_typeof(partido.torneo_id)::text, pg_typeof(fixture.torneo_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'visitante', pg_typeof(partido.visitante)::text, pg_typeof(fixture.visitante)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'visitante_id', pg_typeof(partido.visitante_id)::text, pg_typeof(fixture.visitante_id)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
    union all
    select 'zona', pg_typeof(partido.zona)::text, pg_typeof(fixture.zona)::text
    from (select * from public.partidos where torneo_id = 1 limit 1) partido cross join (select * from fixture limit 1) fixture
  ) typed
),
type_summary as (
  select
    count(*) filter (where not ok) as invalidos,
    coalesce(
      string_agg(campo || ':' || tipo_partidos || '<>' || tipo_fixture, '; ' order by campo)
        filter (where not ok),
      ''
    ) as detalle
  from type_checks
),
resumen as (
  select
    (select total from fixture_total) as fixture_total,
    (select total from clausura) as existentes_clausura,
    (select total from conflictos) as conflictos,
    (
      (select total from fixture_invalidos) = 0
      and (select total from fixture_duplicados) = 0
      and (select total from clubes_invalidos) = 0
      and (select total from apertura) = 140
    ) as zonas_validas,
    (select invalidos from type_summary) = 0 as tipos_validos,
    (select detalle from type_summary) as detalle_tipos
)
select
  fixture_total,
  existentes_clausura,
  conflictos,
  zonas_validas,
  tipos_validos,
  case
    when fixture_total = 114
      and existentes_clausura = 0
      and conflictos = 0
      and zonas_validas
      and tipos_validos
    then 'OK'
    else 'BLOQUEADO'
  end as resultado_final,
  detalle_tipos
from resumen;
